// cl: /O2 /Ob0 /DNDEBUG /MD /EHsc
// Open-BFME5: clean C++ conversion of the positional ViewShake dispatch.

struct Coord3D
{
	float x, y, z;
};

class Matrix3D;

#define BFME_VIEW_SLOT( name ) virtual void name();
class TacticalView
{
public:
	BFME_VIEW_SLOT(v000) BFME_VIEW_SLOT(v004) BFME_VIEW_SLOT(v008) BFME_VIEW_SLOT(v00C)
	BFME_VIEW_SLOT(v010) BFME_VIEW_SLOT(v014) BFME_VIEW_SLOT(v018) BFME_VIEW_SLOT(v01C)
	BFME_VIEW_SLOT(v020) BFME_VIEW_SLOT(v024) BFME_VIEW_SLOT(v028) BFME_VIEW_SLOT(v02C)
	BFME_VIEW_SLOT(v030) BFME_VIEW_SLOT(v034) BFME_VIEW_SLOT(v038) BFME_VIEW_SLOT(v03C)
	BFME_VIEW_SLOT(v040) BFME_VIEW_SLOT(v044) BFME_VIEW_SLOT(v048) BFME_VIEW_SLOT(v04C)
	BFME_VIEW_SLOT(v050) BFME_VIEW_SLOT(v054) BFME_VIEW_SLOT(v058) BFME_VIEW_SLOT(v05C)
	BFME_VIEW_SLOT(v060) BFME_VIEW_SLOT(v064) BFME_VIEW_SLOT(v068) BFME_VIEW_SLOT(v06C)
	BFME_VIEW_SLOT(v070) BFME_VIEW_SLOT(v074) BFME_VIEW_SLOT(v078) BFME_VIEW_SLOT(v07C)
	BFME_VIEW_SLOT(v080) BFME_VIEW_SLOT(v084) BFME_VIEW_SLOT(v088) BFME_VIEW_SLOT(v08C)
	BFME_VIEW_SLOT(v090) BFME_VIEW_SLOT(v094) BFME_VIEW_SLOT(v098) BFME_VIEW_SLOT(v09C)
	BFME_VIEW_SLOT(v0A0) BFME_VIEW_SLOT(v0A4) BFME_VIEW_SLOT(v0A8) BFME_VIEW_SLOT(v0AC)
	BFME_VIEW_SLOT(v0B0) BFME_VIEW_SLOT(v0B4) BFME_VIEW_SLOT(v0B8) BFME_VIEW_SLOT(v0BC)
	BFME_VIEW_SLOT(v0C0) BFME_VIEW_SLOT(v0C4) BFME_VIEW_SLOT(v0C8) BFME_VIEW_SLOT(v0CC)
	BFME_VIEW_SLOT(v0D0) BFME_VIEW_SLOT(v0D4) BFME_VIEW_SLOT(v0D8) BFME_VIEW_SLOT(v0DC)
	BFME_VIEW_SLOT(v0E0) BFME_VIEW_SLOT(v0E4) BFME_VIEW_SLOT(v0E8) BFME_VIEW_SLOT(v0EC)
	BFME_VIEW_SLOT(v0F0) BFME_VIEW_SLOT(v0F4) BFME_VIEW_SLOT(v0F8) BFME_VIEW_SLOT(v0FC)
	BFME_VIEW_SLOT(v100) BFME_VIEW_SLOT(v104) BFME_VIEW_SLOT(v108) BFME_VIEW_SLOT(v10C)
	BFME_VIEW_SLOT(v110) BFME_VIEW_SLOT(v114) BFME_VIEW_SLOT(v118) BFME_VIEW_SLOT(v11C)
	BFME_VIEW_SLOT(v120) BFME_VIEW_SLOT(v124) BFME_VIEW_SLOT(v128) BFME_VIEW_SLOT(v12C)
	BFME_VIEW_SLOT(v130) BFME_VIEW_SLOT(v134) BFME_VIEW_SLOT(v138) BFME_VIEW_SLOT(v13C)
	BFME_VIEW_SLOT(v140) BFME_VIEW_SLOT(v144) BFME_VIEW_SLOT(v148) BFME_VIEW_SLOT(v14C)
	BFME_VIEW_SLOT(v150) BFME_VIEW_SLOT(v154) BFME_VIEW_SLOT(v158) BFME_VIEW_SLOT(v15C)
	BFME_VIEW_SLOT(v160) BFME_VIEW_SLOT(v164) BFME_VIEW_SLOT(v168) BFME_VIEW_SLOT(v16C)
	BFME_VIEW_SLOT(v170) BFME_VIEW_SLOT(v174) BFME_VIEW_SLOT(v178) BFME_VIEW_SLOT(v17C)
	BFME_VIEW_SLOT(v180) BFME_VIEW_SLOT(v184) BFME_VIEW_SLOT(v188) BFME_VIEW_SLOT(v18C)
	BFME_VIEW_SLOT(v190) BFME_VIEW_SLOT(v194) BFME_VIEW_SLOT(v198) BFME_VIEW_SLOT(v19C)
	BFME_VIEW_SLOT(v1A0) BFME_VIEW_SLOT(v1A4)
	virtual void shake(const Coord3D *, int);
};
#undef BFME_VIEW_SLOT

extern TacticalView *TheTacticalView;

class ViewShakeFXNugget
{
public:
	virtual void v00();
	virtual void doFXPos(const Coord3D *, const Matrix3D *, float, const Coord3D *) const;

private:
	unsigned char m_unmodelled[0xB0];
	int m_shake;
};

// ?doFXPos@ViewShakeFXNugget@@UBEXPBUCoord3D@@PBVMatrix3D@@M0@Z
void ViewShakeFXNugget::doFXPos(const Coord3D *primary, const Matrix3D *, float,
	const Coord3D *) const
{
	if (primary && TheTacticalView)
		TheTacticalView->shake(primary, m_shake);
}
