// cl: /DNDEBUG /MD /EHsc

// BFME's replacement for the Zero Hour GUI message sound.  The retail helper
// is a static function: it asks the client audio subsystem for its MiscAudio
// block and queues the event at offset +0xC40.

class ClientSubsystem
{
public:
#define CLIENT_SUBSYSTEM_SLOT(number) virtual void slot##number();
	CLIENT_SUBSYSTEM_SLOT(00) CLIENT_SUBSYSTEM_SLOT(01)
	CLIENT_SUBSYSTEM_SLOT(02) CLIENT_SUBSYSTEM_SLOT(03)
	CLIENT_SUBSYSTEM_SLOT(04) CLIENT_SUBSYSTEM_SLOT(05)
	CLIENT_SUBSYSTEM_SLOT(06) CLIENT_SUBSYSTEM_SLOT(07)
	CLIENT_SUBSYSTEM_SLOT(08) CLIENT_SUBSYSTEM_SLOT(09)
	CLIENT_SUBSYSTEM_SLOT(10) CLIENT_SUBSYSTEM_SLOT(11)
	CLIENT_SUBSYSTEM_SLOT(12) CLIENT_SUBSYSTEM_SLOT(13)
	CLIENT_SUBSYSTEM_SLOT(14) CLIENT_SUBSYSTEM_SLOT(15)
	CLIENT_SUBSYSTEM_SLOT(16)
	virtual void addAudioEvent(void *event);
	CLIENT_SUBSYSTEM_SLOT(18) CLIENT_SUBSYSTEM_SLOT(19)
	CLIENT_SUBSYSTEM_SLOT(20) CLIENT_SUBSYSTEM_SLOT(21)
	CLIENT_SUBSYSTEM_SLOT(22) CLIENT_SUBSYSTEM_SLOT(23)
	CLIENT_SUBSYSTEM_SLOT(24) CLIENT_SUBSYSTEM_SLOT(25)
	CLIENT_SUBSYSTEM_SLOT(26) CLIENT_SUBSYSTEM_SLOT(27)
	CLIENT_SUBSYSTEM_SLOT(28) CLIENT_SUBSYSTEM_SLOT(29)
	CLIENT_SUBSYSTEM_SLOT(30) CLIENT_SUBSYSTEM_SLOT(31)
	CLIENT_SUBSYSTEM_SLOT(32) CLIENT_SUBSYSTEM_SLOT(33)
	CLIENT_SUBSYSTEM_SLOT(34) CLIENT_SUBSYSTEM_SLOT(35)
	CLIENT_SUBSYSTEM_SLOT(36) CLIENT_SUBSYSTEM_SLOT(37)
	CLIENT_SUBSYSTEM_SLOT(38) CLIENT_SUBSYSTEM_SLOT(39)
	CLIENT_SUBSYSTEM_SLOT(40) CLIENT_SUBSYSTEM_SLOT(41)
	CLIENT_SUBSYSTEM_SLOT(42) CLIENT_SUBSYSTEM_SLOT(43)
	CLIENT_SUBSYSTEM_SLOT(44) CLIENT_SUBSYSTEM_SLOT(45)
	CLIENT_SUBSYSTEM_SLOT(46) CLIENT_SUBSYSTEM_SLOT(47)
	CLIENT_SUBSYSTEM_SLOT(48) CLIENT_SUBSYSTEM_SLOT(49)
	CLIENT_SUBSYSTEM_SLOT(50) CLIENT_SUBSYSTEM_SLOT(51)
	CLIENT_SUBSYSTEM_SLOT(52) CLIENT_SUBSYSTEM_SLOT(53)
	CLIENT_SUBSYSTEM_SLOT(54) CLIENT_SUBSYSTEM_SLOT(55)
	CLIENT_SUBSYSTEM_SLOT(56) CLIENT_SUBSYSTEM_SLOT(57)
	CLIENT_SUBSYSTEM_SLOT(58) CLIENT_SUBSYSTEM_SLOT(59)
	CLIENT_SUBSYSTEM_SLOT(60) CLIENT_SUBSYSTEM_SLOT(61)
	CLIENT_SUBSYSTEM_SLOT(62) CLIENT_SUBSYSTEM_SLOT(63)
	CLIENT_SUBSYSTEM_SLOT(64) CLIENT_SUBSYSTEM_SLOT(65)
	CLIENT_SUBSYSTEM_SLOT(66) CLIENT_SUBSYSTEM_SLOT(67)
	CLIENT_SUBSYSTEM_SLOT(68) CLIENT_SUBSYSTEM_SLOT(69)
	CLIENT_SUBSYSTEM_SLOT(70) CLIENT_SUBSYSTEM_SLOT(71)
	CLIENT_SUBSYSTEM_SLOT(72)
	virtual void *getMiscAudio();
#undef CLIENT_SUBSYSTEM_SLOT
};

extern ClientSubsystem *TheAudioClientUpdate;

class BFMEConnectionManager
{
public:
	static void playMessageReceivedSound();
};

// ?playMessageReceivedSound@BFMEConnectionManager@@SAXXZ
void BFMEConnectionManager::playMessageReceivedSound()
{
	if (TheAudioClientUpdate == 0)
		return;

	char *miscAudio = reinterpret_cast<char *>(
		TheAudioClientUpdate->getMiscAudio());
	if (miscAudio == 0)
		return;

	TheAudioClientUpdate->addAudioEvent(miscAudio + 0xC40);
}
