class BfmeThingARA
{
public:
	virtual void bfmeSpareARA0();
	virtual void bfmeSpareARA1();
	virtual void bfmeSpareARA2();
	virtual void bfmeSpareARA3();
	virtual void bfmeSpareARA4();
	virtual void bfmeSpareARA5();
	virtual void bfmeSpareARA6();
	virtual void bfmeSpareARA7();
	virtual void bfmeSpareARA8();
	virtual void bfmeSpareARA9();
	virtual void bfmeSpareARA10();
	virtual void bfmeSpareARA11();
	virtual void bfmeSpareARA12();
	virtual void bfmeSpareARA13();
	virtual void bfmeSpareARA14();
	virtual void bfmeSpareARA15();
	virtual void bfmeSpareARA16();
	virtual void bfmeSpareARA17();
	virtual void bfmeSpareARA18();
	virtual void bfmeSpareARA19();
	virtual void bfmeSpareARA20();
	virtual void bfmeSpareARA21();
	virtual void bfmeSpareARA22();
	virtual void bfmeSpareARA23();
	virtual void bfmeSpareARA24();
	virtual void bfmeSpareARA25();
	virtual void bfmeSpareARA26();
	virtual void bfmeSpareARA27();
	virtual void bfmeSpareARA28();
	virtual void bfmeSpareARA29();
	virtual void bfmeSpareARA30();
	virtual void bfmeSpareARA31();
	virtual void bfmeSpareARA32();
	virtual void bfmeSpareARA33();
	virtual void bfmeSpareARA34();
	virtual void bfmeSpareARA35();
	virtual void bfmeSpareARA36();
	virtual void bfmeSpareARA37();
	virtual void bfmeSpareARA38();
	virtual void bfmeSpareARA39();
	virtual void bfmeSpareARA40();
	virtual void bfmeSpareARA41();
	virtual void bfmeSpareARA42();
	virtual void bfmeSpareARA43();
	virtual void bfmeSpareARA44();
	virtual void bfmeSpareARA45();
	virtual void bfmeSpareARA46();
	virtual void bfmeSpareARA47();
	virtual void bfmeSpareARA48();
	virtual void bfmeSpareARA49();
	virtual void bfmeSpareARA50();
	virtual void bfmeSpareARA51();
	virtual void bfmeSpareARA52();
	virtual void bfmeSpareARA53();
	virtual void bfmeSpareARA54();
	virtual void bfmeSpareARA55();
	virtual void bfmeSpareARA56();
	virtual void bfmeSpareARA57();
	virtual void bfmeSpareARA58();
	virtual void bfmeSpareARA59();
	virtual void bfmeSpareARA60();
	virtual void bfmeSpareARA61();
	virtual void bfmeSpareARA62();
	virtual void bfmeSpareARA63();
	virtual void bfmeSpareARA64();
	virtual void bfmeSpareARA65();
	virtual void bfmeSpareARA66();
	virtual void bfmeSpareARA67();
	virtual void bfmeSpareARA68();
	virtual void bfmeSpareARA69();
	virtual void bfmeSpareARA70();
	virtual void bfmeSpareARA71();
	virtual void bfmeSpareARA72();
	virtual void bfmeSpareARA73();
	virtual void bfmeSpareARA74();
	virtual void bfmeSpareARA75();
	virtual void bfmeSpareARA76();
	virtual void bfmeSpareARA77();
	virtual void bfmeSpareARA78();
	virtual void bfmeSpareARA79();
	virtual void bfmeSpareARA80();
	virtual void bfmeSpareARA81();
	virtual void bfmeSpareARA82();
	virtual void bfmeSpareARA83();
	virtual void bfmeSpareARA84();
	virtual void bfmeSpareARA85();
	virtual void bfmeSpareARA86();
	virtual void bfmeSpareARA87();
	virtual void bfmeSpareARA88();
	virtual void bfmeSpareARA89();
	virtual void bfmeSpareARA90();
	virtual void bfmeSpareARA91();
	virtual void bfmeSpareARA92();
	virtual void bfmeSpareARA93();
	virtual void bfmeTailARA();
	void bfmeStepARA();
	void bfmeGoARA();
	unsigned char m_bfmeHeadOne[0x6c - 4];
	unsigned int m_bfmeOne;
	unsigned int m_bfmeTwo;
	unsigned char m_bfmeGap[0x242a - 0x74];
	bool m_bfmeFlag;
};

void BfmeThingARA::bfmeGoARA()
{
	m_bfmeFlag = false;
	m_bfmeTwo = 0x3f800000;
	m_bfmeOne = 0x3f5f66f3;
	bfmeStepARA();
	bfmeTailARA();
}
