// cl: /DNDEBUG /MD /EHsc
// readable body of ??0AIAttackMoveToState@@QAE@PAVStateMachine@@@Z: Code/GameEngine/Source/GameLogic/AI/AIStates.cpp

class StateMachine;

// upstream layout: reference/CnC_Generals_Zero_Hour/GeneralsMD/Code/GameEngine/Include/GameLogic/AIStateMachine.h
class AIAttackMoveToState
{
public:
    AIAttackMoveToState(StateMachine*);
};

__declspec(naked) AIAttackMoveToState::AIAttackMoveToState(StateMachine*)
{
    __asm {
        _emit 6Ah
        _emit 0FFh
        _emit 68h
        _emit 7Bh
        _emit 62h
        _emit 00h
        _emit 01h
        _emit 64h
        _emit 0A1h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 50h
        _emit 64h
        _emit 89h
        _emit 25h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 83h
        _emit 0ECh
        _emit 08h
        _emit 53h
        _emit 56h
        _emit 8Bh
        _emit 0F1h
        _emit 57h
        _emit 89h
        _emit 74h
        _emit 24h
        _emit 0Ch
        _emit 51h
        _emit 8Dh
        _emit 44h
        _emit 24h
        _emit 30h
        _emit 89h
        _emit 64h
        _emit 24h
        _emit 14h
        _emit 8Bh
        _emit 0CCh
        _emit 33h
        _emit 0DBh
        _emit 50h
        _emit 89h
        _emit 5Ch
        _emit 24h
        _emit 24h
        _emit 0E8h
        _emit 98h
        _emit 41h
        _emit 70h
        _emit 00h
        _emit 8Bh
        _emit 4Ch
        _emit 24h
        _emit 28h
        _emit 51h
        _emit 8Bh
        _emit 0CEh
        _emit 0E8h
        _emit 0AEh
        _emit 0E7h
        _emit 0EAh
        _emit 0FFh
        _emit 38h
        _emit 5Ch
        _emit 24h
        _emit 28h
        _emit 0C6h
        _emit 44h
        _emit 24h
        _emit 1Ch
        _emit 01h
        _emit 0C7h
        _emit 06h
        _emit 08h
        _emit 9Ch
        _emit 09h
        _emit 01h
        _emit 89h
        _emit 5Eh
        _emit 50h
        _emit 0C7h
        _emit 46h
        _emit 54h
        _emit 05h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 0C6h
        _emit 46h
        _emit 58h
        _emit 01h
        _emit 88h
        _emit 5Eh
        _emit 59h
        _emit 88h
        _emit 5Eh
        _emit 5Ah
        _emit 88h
        _emit 5Eh
        _emit 5Bh
        _emit 89h
        _emit 5Eh
        _emit 5Ch
        _emit 89h
        _emit 5Eh
        _emit 60h
        _emit 89h
        _emit 5Eh
        _emit 64h
        _emit 88h
        _emit 5Eh
        _emit 68h
        _emit 74h
        _emit 4Bh
        _emit 6Ah
        _emit 44h
        _emit 0E8h
        _emit 21h
        _emit 0E5h
        _emit 6Fh
        _emit 00h
        _emit 8Bh
        _emit 0F8h
        _emit 83h
        _emit 0C4h
        _emit 04h
        _emit 89h
        _emit 7Ch
        _emit 24h
        _emit 28h
        _emit 3Bh
        _emit 0FBh
        _emit 0C6h
        _emit 44h
        _emit 24h
        _emit 1Ch
        _emit 02h
        _emit 74h
        _emit 21h
        _emit 51h
        _emit 89h
        _emit 64h
        _emit 24h
        _emit 28h
        _emit 8Bh
        _emit 0CCh
        _emit 68h
        _emit 78h
        _emit 0B1h
        _emit 09h
        _emit 01h
        _emit 0E8h
        _emit 8Eh
        _emit 51h
        _emit 70h
        _emit 00h
        _emit 8Bh
        _emit 56h
        _emit 1Ch
        _emit 8Bh
        _emit 42h
        _emit 10h
        _emit 50h
        _emit 8Bh
        _emit 0CFh
        _emit 0E8h
        _emit 68h
        _emit 0A5h
        _emit 0E8h
        _emit 0FFh
        _emit 0EBh
        _emit 02h
        _emit 33h
        _emit 0C0h
        _emit 89h
        _emit 46h
        _emit 60h
        _emit 8Bh
        _emit 10h
        _emit 8Bh
        _emit 0C8h
        _emit 0C6h
        _emit 44h
        _emit 24h
        _emit 1Ch
        _emit 01h
        _emit 0FFh
        _emit 52h
        _emit 1Ch
        _emit 8Dh
        _emit 4Ch
        _emit 24h
        _emit 2Ch
        _emit 0C7h
        _emit 44h
        _emit 24h
        _emit 1Ch
        _emit 0FFh
        _emit 0FFh
        _emit 0FFh
        _emit 0FFh
        _emit 0E8h
        _emit 0DCh
        _emit 3Eh
        _emit 70h
        _emit 00h
        _emit 8Bh
        _emit 4Ch
        _emit 24h
        _emit 14h
        _emit 5Fh
        _emit 8Bh
        _emit 0C6h
        _emit 5Eh
        _emit 64h
        _emit 89h
        _emit 0Dh
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 5Bh
        _emit 83h
        _emit 0C4h
        _emit 14h
        _emit 0C2h
        _emit 0Ch
        _emit 00h
    }
}

