// cl: /DNDEBUG /MD /EHsc

class Thing;
class ModuleData;

// upstream layout: reference/CnC_Generals_Zero_Hour/GeneralsMD/Code/GameEngine/Include/GameLogic/Module/AssistedTargetingUpdate.h
class AssistedTargetingUpdate
{
public:
    AssistedTargetingUpdate(Thing*, const ModuleData*);
};

__declspec(naked) AssistedTargetingUpdate::AssistedTargetingUpdate(Thing*, const ModuleData*)
{
    __asm {
        _emit 6Ah
        _emit 0FFh
        _emit 68h
        _emit 0F8h
        _emit 07h
        _emit 01h
        _emit 01h
        _emit 64h
        _emit 0A1h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 50h
        _emit 64h
        _emit 89h
        _emit 25h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 51h
        _emit 8Bh
        _emit 44h
        _emit 24h
        _emit 18h
        _emit 56h
        _emit 8Bh
        _emit 0F1h
        _emit 8Bh
        _emit 4Ch
        _emit 24h
        _emit 18h
        _emit 50h
        _emit 51h
        _emit 8Bh
        _emit 0CEh
        _emit 89h
        _emit 74h
        _emit 24h
        _emit 0Ch
        _emit 0E8h
        _emit 56h
        _emit 75h
        _emit 0D9h
        _emit 0FFh
        _emit 0C7h
        _emit 46h
        _emit 0Ch
        _emit 0D0h
        _emit 0C9h
        _emit 09h
        _emit 01h
        _emit 0C7h
        _emit 46h
        _emit 10h
        _emit 0A0h
        _emit 0CBh
        _emit 09h
        _emit 01h
        _emit 83h
        _emit 0C8h
        _emit 0FFh
        _emit 33h
        _emit 0C9h
        _emit 89h
        _emit 4Eh
        _emit 14h
        _emit 89h
        _emit 46h
        _emit 18h
        _emit 89h
        _emit 46h
        _emit 1Ch
        _emit 8Bh
        _emit 56h
        _emit 08h
        _emit 68h
        _emit 0FFh
        _emit 0FFh
        _emit 0FFh
        _emit 3Fh
        _emit 89h
        _emit 4Ch
        _emit 24h
        _emit 14h
        _emit 52h
        _emit 8Bh
        _emit 0CEh
        _emit 0C7h
        _emit 06h
        _emit 0D4h
        _emit 0ACh
        _emit 0Bh
        _emit 01h
        _emit 0C7h
        _emit 46h
        _emit 0Ch
        _emit 10h
        _emit 0ACh
        _emit 0Bh
        _emit 01h
        _emit 0C7h
        _emit 46h
        _emit 10h
        _emit 00h
        _emit 0ACh
        _emit 0Bh
        _emit 01h
        _emit 0E8h
        _emit 08h
        _emit 5Ch
        _emit 0D9h
        _emit 0FFh
        _emit 8Bh
        _emit 4Ch
        _emit 24h
        _emit 08h
        _emit 8Bh
        _emit 0C6h
        _emit 5Eh
        _emit 64h
        _emit 89h
        _emit 0Dh
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 83h
        _emit 0C4h
        _emit 10h
        _emit 0C2h
        _emit 08h
        _emit 00h
    }
}
