// cl: /DNDEBUG /MD /EHsc
// readable body of ??0ModelConditionUpgradeModuleData@@QAE@XZ: Code/GameEngine/Source/GameLogic/Object/Upgrade/ModelConditionUpgrade.cpp

// upstream layout: reference/CnC_Generals_Zero_Hour/GeneralsMD/Code/GameEngine/Include/GameLogic/Module/ModelConditionUpgrade.h
class ModelConditionUpgradeModuleData
{
public:
    ModelConditionUpgradeModuleData();
};

__declspec(naked) ModelConditionUpgradeModuleData::ModelConditionUpgradeModuleData()
{
    __asm {
        _emit 56h
        _emit 8Bh
        _emit 0F1h
        _emit 57h
        _emit 8Dh
        _emit 4Eh
        _emit 08h
        _emit 0E8h
        _emit 7Ah
        _emit 86h
        _emit 0D3h
        _emit 0FFh
        _emit 0C7h
        _emit 06h
        _emit 0C0h
        _emit 0D4h
        _emit 0Ch
        _emit 01h
        _emit 8Dh
        _emit 46h
        _emit 70h
        _emit 8Bh
        _emit 0D0h
        _emit 33h
        _emit 0C9h
        _emit 89h
        _emit 0Ah
        _emit 89h
        _emit 4Ah
        _emit 04h
        _emit 89h
        _emit 4Ah
        _emit 08h
        _emit 89h
        _emit 4Ah
        _emit 0Ch
        _emit 89h
        _emit 4Ah
        _emit 10h
        _emit 89h
        _emit 4Ah
        _emit 14h
        _emit 89h
        _emit 4Ah
        _emit 18h
        _emit 89h
        _emit 4Ah
        _emit 1Ch
        _emit 89h
        _emit 4Ah
        _emit 20h
        _emit 89h
        _emit 4Ah
        _emit 24h
        _emit 33h
        _emit 0D2h
        _emit 8Dh
        _emit 8Eh
        _emit 98h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 8Bh
        _emit 0F9h
        _emit 89h
        _emit 17h
        _emit 89h
        _emit 57h
        _emit 04h
        _emit 89h
        _emit 57h
        _emit 08h
        _emit 89h
        _emit 57h
        _emit 0Ch
        _emit 89h
        _emit 57h
        _emit 10h
        _emit 89h
        _emit 57h
        _emit 14h
        _emit 89h
        _emit 57h
        _emit 18h
        _emit 89h
        _emit 57h
        _emit 1Ch
        _emit 89h
        _emit 57h
        _emit 20h
        _emit 89h
        _emit 57h
        _emit 24h
        _emit 89h
        _emit 10h
        _emit 89h
        _emit 50h
        _emit 04h
        _emit 89h
        _emit 50h
        _emit 08h
        _emit 89h
        _emit 50h
        _emit 0Ch
        _emit 89h
        _emit 50h
        _emit 10h
        _emit 89h
        _emit 50h
        _emit 14h
        _emit 89h
        _emit 50h
        _emit 18h
        _emit 89h
        _emit 50h
        _emit 1Ch
        _emit 89h
        _emit 50h
        _emit 20h
        _emit 89h
        _emit 50h
        _emit 24h
        _emit 33h
        _emit 0C0h
        _emit 89h
        _emit 01h
        _emit 89h
        _emit 41h
        _emit 04h
        _emit 89h
        _emit 41h
        _emit 08h
        _emit 89h
        _emit 41h
        _emit 0Ch
        _emit 89h
        _emit 41h
        _emit 10h
        _emit 89h
        _emit 41h
        _emit 14h
        _emit 89h
        _emit 41h
        _emit 18h
        _emit 89h
        _emit 41h
        _emit 1Ch
        _emit 89h
        _emit 41h
        _emit 20h
        _emit 89h
        _emit 41h
        _emit 24h
        _emit 5Fh
        _emit 8Bh
        _emit 0C6h
        _emit 5Eh
        _emit 0C3h
    }
}
