// cl: /DNDEBUG /MD /EHsc

// upstream layout: reference/CnC_Generals_Zero_Hour/GeneralsMD/Code/GameEngine/Include/GameLogic/Module/MoneyCrateCollide.h
class MoneyCrateCollideModuleData
{
public:
    MoneyCrateCollideModuleData();
};

__declspec(naked) MoneyCrateCollideModuleData::MoneyCrateCollideModuleData()
{
    __asm {
        _emit 6Ah
        _emit 0FFh
        _emit 68h
        _emit 58h
        _emit 0CBh
        _emit 00h
        _emit 01h
        _emit 64h
        _emit 0A1h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 50h
        _emit 64h
        _emit 89h
        _emit 25h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 51h
        _emit 53h
        _emit 56h
        _emit 8Bh
        _emit 0F1h
        _emit 89h
        _emit 74h
        _emit 24h
        _emit 08h
        _emit 0C7h
        _emit 06h
        _emit 78h
        _emit 0A3h
        _emit 0Ah
        _emit 01h
        _emit 33h
        _emit 0C0h
        _emit 8Dh
        _emit 4Eh
        _emit 08h
        _emit 89h
        _emit 01h
        _emit 89h
        _emit 41h
        _emit 04h
        _emit 89h
        _emit 41h
        _emit 08h
        _emit 89h
        _emit 41h
        _emit 0Ch
        _emit 89h
        _emit 41h
        _emit 10h
        _emit 89h
        _emit 41h
        _emit 14h
        _emit 33h
        _emit 0D2h
        _emit 8Dh
        _emit 46h
        _emit 20h
        _emit 89h
        _emit 10h
        _emit 89h
        _emit 50h
        _emit 04h
        _emit 89h
        _emit 50h
        _emit 08h
        _emit 89h
        _emit 50h
        _emit 0Ch
        _emit 89h
        _emit 50h
        _emit 10h
        _emit 33h
        _emit 0DBh
        _emit 89h
        _emit 50h
        _emit 14h
        _emit 68h
        _emit 50h
        _emit 6Eh
        _emit 33h
        _emit 01h
        _emit 8Dh
        _emit 4Eh
        _emit 44h
        _emit 89h
        _emit 5Ch
        _emit 24h
        _emit 18h
        _emit 88h
        _emit 5Eh
        _emit 38h
        _emit 88h
        _emit 5Eh
        _emit 39h
        _emit 88h
        _emit 5Eh
        _emit 3Ah
        _emit 0C7h
        _emit 46h
        _emit 3Ch
        _emit 0FFh
        _emit 0FFh
        _emit 0FFh
        _emit 0FFh
        _emit 89h
        _emit 5Eh
        _emit 40h
        _emit 0E8h
        _emit 7Ah
        _emit 02h
        _emit 67h
        _emit 00h
        _emit 8Bh
        _emit 4Ch
        _emit 24h
        _emit 0Ch
        _emit 89h
        _emit 5Eh
        _emit 48h
        _emit 89h
        _emit 5Eh
        _emit 4Ch
        _emit 0C6h
        _emit 46h
        _emit 50h
        _emit 01h
        _emit 8Bh
        _emit 0C6h
        _emit 5Eh
        _emit 5Bh
        _emit 64h
        _emit 89h
        _emit 0Dh
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 83h
        _emit 0C4h
        _emit 10h
        _emit 0C3h
    }
}

