// cl: /DNDEBUG /MD /EHsc
// readable body of ??0ProductionUpdateModuleData@@: Code/GameEngine/Source/GameLogic/Object/Update/ProductionUpdate.cpp

// upstream layout: reference/CnC_Generals_Zero_Hour/GeneralsMD/Code/GameEngine/Include/GameLogic/Module/ProductionUpdate.h
class ProductionUpdateModuleData
{
public:
    ProductionUpdateModuleData();
};

__declspec(naked) ProductionUpdateModuleData::ProductionUpdateModuleData()
{
    __asm {
        _emit 6Ah
        _emit 0FFh
        _emit 68h
        _emit 69h
        _emit 24h
        _emit 01h
        _emit 01h
        _emit 64h
        _emit 0A1h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 50h
        _emit 64h
        _emit 89h
        _emit 25h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 51h
        _emit 53h
        _emit 56h
        _emit 8Bh
        _emit 0F1h
        _emit 57h
        _emit 89h
        _emit 74h
        _emit 24h
        _emit 0Ch
        _emit 33h
        _emit 0DBh
        _emit 8Dh
        _emit 4Eh
        _emit 1Ch
        _emit 0C7h
        _emit 06h
        _emit 68h
        _emit 0Fh
        _emit 0Ch
        _emit 01h
        _emit 89h
        _emit 19h
        _emit 89h
        _emit 59h
        _emit 04h
        _emit 89h
        _emit 5Ch
        _emit 24h
        _emit 18h
        _emit 89h
        _emit 59h
        _emit 08h
        _emit 8Dh
        _emit 7Eh
        _emit 40h
        _emit 89h
        _emit 5Eh
        _emit 2Ch
        _emit 89h
        _emit 1Fh
        _emit 89h
        _emit 5Eh
        _emit 44h
        _emit 89h
        _emit 5Eh
        _emit 08h
        _emit 89h
        _emit 5Eh
        _emit 0Ch
        _emit 89h
        _emit 5Eh
        _emit 10h
        _emit 89h
        _emit 5Eh
        _emit 14h
        _emit 89h
        _emit 5Eh
        _emit 18h
        _emit 8Bh
        _emit 41h
        _emit 04h
        _emit 8Bh
        _emit 11h
        _emit 50h
        _emit 52h
        _emit 0C6h
        _emit 44h
        _emit 24h
        _emit 20h
        _emit 03h
        _emit 0E8h
        _emit 6Ah
        _emit 26h
        _emit 0D9h
        _emit 0FFh
        _emit 53h
        _emit 68h
        _emit 1Ch
        _emit 30h
        _emit 07h
        _emit 01h
        _emit 8Bh
        _emit 0CFh
        _emit 0C7h
        _emit 46h
        _emit 28h
        _emit 14h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 0C7h
        _emit 46h
        _emit 2Ch
        _emit 08h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 88h
        _emit 5Eh
        _emit 30h
        _emit 89h
        _emit 5Eh
        _emit 34h
        _emit 89h
        _emit 5Eh
        _emit 38h
        _emit 88h
        _emit 5Eh
        _emit 3Ch
        _emit 88h
        _emit 5Eh
        _emit 3Dh
        _emit 0E8h
        _emit 25h
        _emit 81h
        _emit 5Eh
        _emit 00h
        _emit 8Bh
        _emit 4Ch
        _emit 24h
        _emit 10h
        _emit 5Fh
        _emit 8Bh
        _emit 0C6h
        _emit 5Eh
        _emit 5Bh
        _emit 64h
        _emit 89h
        _emit 0Dh
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 00h
        _emit 83h
        _emit 0C4h
        _emit 10h
        _emit 0C3h
    }
}
